### ISSUE TITLE
[Proposal] Transfer '<<' operator

### ISSUE THREAD

**Issue by MaxGraey** [lrettig/ewasm-as-wrc20#1]
For EOS smart contracts I proposed [this](https://github.com/eos-typescript/examples/issues/1#issuecomment-394988073) high-level transfer operator:

```ts
function transfer(sender: Address, recipient: Address, quantity: Amount): void {
   Account.get(recipient) << quantity << Account.get(sender);
}
```
WDYT about this convention also for ewasm smart contracts?

**Comment by lrettig** [comment]
https://github.com/etherts/ewasm-as/ is the right repo for this! Let's move the conversation to https://github.com/etherts/ewasm-as/issues/4
